// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDdjFcwAGNDTIwh0y-8i0UXhwboN_yg8',
    appId: '1:734996712545:web:dbd77395ccce5565b52e20',
    messagingSenderId: '734996712545',
    projectId: 'daleel-df56f',
    authDomain: 'daleel-df56f.firebaseapp.com',
    storageBucket: 'daleel-df56f.appspot.com',
    measurementId: 'G-6REMEDEPD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5R3AUasYr11yKnlpYmxa1om4lwJsRHZA',
    appId: '1:734996712545:android:3fbf05b9a1ed3d9db52e20',
    messagingSenderId: '734996712545',
    projectId: 'daleel-df56f',
    storageBucket: 'daleel-df56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWGPXjmim2CiYQTlF26UAZpzM0k8fLM8',
    appId: '1:734996712545:ios:29872fbbdabe8073b52e20',
    messagingSenderId: '734996712545',
    projectId: 'daleel-df56f',
    storageBucket: 'daleel-df56f.appspot.com',
    iosClientId: '734996712545-3fphemn277de0i07i7j2m8sliu2dgpun.apps.googleusercontent.com',
    iosBundleId: 'com.daleel.vendors',
  );
}
